### ISSUE TITLE
CapGun can't deliver mail in Rails 2.3.3 and newer

### ISSUE THREAD

**Issue by rsanheim** [relevance/cap_gun#2]
Blocked by this issue in Rails:

https://rails.lighthouseapp.com/projects/8994/tickets/2340

**Comment by deadprogram** [comment]
A quick and dirty solution to this is simply changing the syntax you use for the cap_gun_email_envelope params. Where the original blog post suggests:

set :cap_gun_email_envelope, {
  :recipients => %w[fooproj-devs@example.com fooproj-mgr@example.com], 
  :from => "Foo Project Deployment Bot grey-goo@example.com"
}

instead use

set :cap_gun_email_envelope, {
  :recipients => %w[fooproj-devs@example.com fooproj-mgr@example.com], 
  :from => "grey-goo@example.com"
}

That will avoid the syntax parsing error for the :from address.

**Comment by ghost** [comment]
Thanks for the tip.  Added a note re the workaround in the README.
