### ISSUE TITLE
CapGun when its run on a brand new deploy, because there is no REVISION directory

### ISSUE THREAD

**Issue by rsanheim** [relevance/cap_gun#3]
fails on

```
cat: /REVISION no such file or directory
```

We should ignore this error for fresh deploys

**Comment by pboling** [comment]
CapistranoMailer (the 'other' gem in the same domain as CapGun) has the 'same' problem... I've never really looked into how to fix it, because it is just a one time thing.  But I'll be watching this ticket to see if you do fix it!

**Comment by jdpace** [comment]
This issue was caused by there not being a previous release: "cat #{previous_release}/REVISION" => "cat /REVISION" This is fixed in 0.2.3

**Comment by rsanheim** [comment]
Fixed in 0.2.4:
